CREATE DATABASE IF NOT EXISTS bankapp;

USE bankapp;

CREATE TABLE IF NOT EXISTS users (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(255),
  Surname VARCHAR(255),
  Email VARCHAR(255),
  Password VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS admins (
  UserID INT PRIMARY KEY,
  AdminPass VARCHAR(255),
  FOREIGN KEY (UserID) REFERENCES users(ID)
);

CREATE TABLE IF NOT EXISTS accounts (
  Number INT AUTO_INCREMENT PRIMARY KEY,
  Owner INT,
  Type INT,
  Value DECIMAL(10,2),
  Currency VARCHAR(10),
  FOREIGN KEY (Owner) REFERENCES users(ID)
);

CREATE TABLE IF NOT EXISTS log (
  User VARCHAR(255),
  LogMessage VARCHAR(255)
);